/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

import org.openapitools.ApiException;
import org.openapitools.client.model.DataPageEffectSchema;
import org.openapitools.client.model.EffectResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EffectsApi
 */
@Disabled
public class EffectsApiTest {

    private final EffectsApi api = new EffectsApi();

    /**
     * Get All Effects
     *
     * List of all effects. Effects are used by equipment, tools, runes, consumables and monsters. An effect is an action that produces an effect on the game.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllEffectsEffectsGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        DataPageEffectSchema response = api.getAllEffectsEffectsGet(page, size);
        // TODO: test validations
    }

    /**
     * Get Effect
     *
     * Retrieve the details of a badge.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEffectEffectsCodeGetTest() throws ApiException {
        String code = null;
        EffectResponseSchema response = api.getEffectEffectsCodeGet(code);
        // TODO: test validations
    }

}
