/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

import org.openapitools.ApiException;
import org.openapitools.client.model.DataPageNPCItem;
import org.openapitools.client.model.DataPageNPCSchema;
import org.openapitools.client.model.NPCResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NpcsApi
 */
@Disabled
public class NpcsApiTest {

    private final NpcsApi api = new NpcsApi();

    /**
     * Get All Npcs
     *
     * Fetch NPCs details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllNpcsNpcsGetTest() throws ApiException {
        String type = null;
        Integer page = null;
        Integer size = null;
        DataPageNPCSchema response = api.getAllNpcsNpcsGet(type, page, size);
        // TODO: test validations
    }

    /**
     * Get Npc Items
     *
     * Retrieve the items list of a NPC. If the NPC has items to buy or sell, they will be displayed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNpcItemsNpcsCodeItemsGetTest() throws ApiException {
        String code = null;
        Integer page = null;
        Integer size = null;
        DataPageNPCItem response = api.getNpcItemsNpcsCodeItemsGet(code, page, size);
        // TODO: test validations
    }

    /**
     * Get Npc
     *
     * Retrieve the details of a NPC.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNpcNpcsCodeGetTest() throws ApiException {
        String code = null;
        NPCResponseSchema response = api.getNpcNpcsCodeGet(code);
        // TODO: test validations
    }

}
