/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

import org.openapitools.ApiCallback;
import org.openapitools.ApiClient;
import org.openapitools.ApiException;
import org.openapitools.ApiResponse;
import org.openapitools.Configuration;
import org.openapitools.Pair;
import org.openapitools.ProgressRequestBody;
import org.openapitools.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AccountLeaderboardType;
import org.openapitools.client.model.CharacterLeaderboardType;
import org.openapitools.client.model.DataPageAccountLeaderboardSchema;
import org.openapitools.client.model.DataPageCharacterLeaderboardSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LeaderboardApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LeaderboardApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LeaderboardApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAccountsLeaderboardLeaderboardAccountsGet
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAccountsLeaderboardLeaderboardAccountsGetCall(AccountLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/leaderboard/accounts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAccountsLeaderboardLeaderboardAccountsGetValidateBeforeCall(AccountLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAccountsLeaderboardLeaderboardAccountsGetCall(sort, name, page, size, _callback);

    }

    /**
     * Get Accounts Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageAccountLeaderboardSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageAccountLeaderboardSchema getAccountsLeaderboardLeaderboardAccountsGet(AccountLeaderboardType sort, String name, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageAccountLeaderboardSchema> localVarResp = getAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(sort, name, page, size);
        return localVarResp.getData();
    }

    /**
     * Get Accounts Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageAccountLeaderboardSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageAccountLeaderboardSchema> getAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(AccountLeaderboardType sort, String name, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAccountsLeaderboardLeaderboardAccountsGetValidateBeforeCall(sort, name, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageAccountLeaderboardSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Accounts Leaderboard (asynchronously)
     * Fetch leaderboard details.
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAccountsLeaderboardLeaderboardAccountsGetAsync(AccountLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback<DataPageAccountLeaderboardSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAccountsLeaderboardLeaderboardAccountsGetValidateBeforeCall(sort, name, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageAccountLeaderboardSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCharactersLeaderboardLeaderboardCharactersGet
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCharactersLeaderboardLeaderboardCharactersGetCall(CharacterLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/leaderboard/characters";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCharactersLeaderboardLeaderboardCharactersGetValidateBeforeCall(CharacterLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getCharactersLeaderboardLeaderboardCharactersGetCall(sort, name, page, size, _callback);

    }

    /**
     * Get Characters Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageCharacterLeaderboardSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageCharacterLeaderboardSchema getCharactersLeaderboardLeaderboardCharactersGet(CharacterLeaderboardType sort, String name, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageCharacterLeaderboardSchema> localVarResp = getCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(sort, name, page, size);
        return localVarResp.getData();
    }

    /**
     * Get Characters Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageCharacterLeaderboardSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageCharacterLeaderboardSchema> getCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(CharacterLeaderboardType sort, String name, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getCharactersLeaderboardLeaderboardCharactersGetValidateBeforeCall(sort, name, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageCharacterLeaderboardSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Characters Leaderboard (asynchronously)
     * Fetch leaderboard details.
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched leaderboard. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCharactersLeaderboardLeaderboardCharactersGetAsync(CharacterLeaderboardType sort, String name, Integer page, Integer size, final ApiCallback<DataPageCharacterLeaderboardSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCharactersLeaderboardLeaderboardCharactersGetValidateBeforeCall(sort, name, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageCharacterLeaderboardSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
