/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

import org.openapitools.ApiCallback;
import org.openapitools.ApiClient;
import org.openapitools.ApiException;
import org.openapitools.ApiResponse;
import org.openapitools.Configuration;
import org.openapitools.Pair;
import org.openapitools.ProgressRequestBody;
import org.openapitools.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageNPCItem;
import org.openapitools.client.model.DataPageNPCSchema;
import org.openapitools.client.model.NPCResponseSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NpcsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public NpcsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public NpcsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllNpcsNpcsGet
     * @param type The type of the NPC. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPCs details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllNpcsNpcsGetCall(String type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/npcs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllNpcsNpcsGetValidateBeforeCall(String type, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllNpcsNpcsGetCall(type, page, size, _callback);

    }

    /**
     * Get All Npcs
     * Fetch NPCs details.
     * @param type The type of the NPC. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageNPCSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPCs details. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageNPCSchema getAllNpcsNpcsGet(String type, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageNPCSchema> localVarResp = getAllNpcsNpcsGetWithHttpInfo(type, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Npcs
     * Fetch NPCs details.
     * @param type The type of the NPC. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageNPCSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPCs details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageNPCSchema> getAllNpcsNpcsGetWithHttpInfo(String type, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllNpcsNpcsGetValidateBeforeCall(type, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageNPCSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Npcs (asynchronously)
     * Fetch NPCs details.
     * @param type The type of the NPC. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPCs details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllNpcsNpcsGetAsync(String type, Integer page, Integer size, final ApiCallback<DataPageNPCSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllNpcsNpcsGetValidateBeforeCall(type, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageNPCSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getNpcItemsNpcsCodeItemsGet
     * @param code The code of the NPC. (required)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getNpcItemsNpcsCodeItemsGetCall(String code, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/npcs/{code}/items"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getNpcItemsNpcsCodeItemsGetValidateBeforeCall(String code, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getNpcItemsNpcsCodeItemsGet(Async)");
        }

        return getNpcItemsNpcsCodeItemsGetCall(code, page, size, _callback);

    }

    /**
     * Get Npc Items
     * Retrieve the items list of a NPC. If the NPC has items to buy or sell, they will be displayed.
     * @param code The code of the NPC. (required)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageNPCItem
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageNPCItem getNpcItemsNpcsCodeItemsGet(String code, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageNPCItem> localVarResp = getNpcItemsNpcsCodeItemsGetWithHttpInfo(code, page, size);
        return localVarResp.getData();
    }

    /**
     * Get Npc Items
     * Retrieve the items list of a NPC. If the NPC has items to buy or sell, they will be displayed.
     * @param code The code of the NPC. (required)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageNPCItem&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageNPCItem> getNpcItemsNpcsCodeItemsGetWithHttpInfo(String code, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getNpcItemsNpcsCodeItemsGetValidateBeforeCall(code, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageNPCItem>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Npc Items (asynchronously)
     * Retrieve the items list of a NPC. If the NPC has items to buy or sell, they will be displayed.
     * @param code The code of the NPC. (required)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getNpcItemsNpcsCodeItemsGetAsync(String code, Integer page, Integer size, final ApiCallback<DataPageNPCItem> _callback) throws ApiException {

        okhttp3.Call localVarCall = getNpcItemsNpcsCodeItemsGetValidateBeforeCall(code, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageNPCItem>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getNpcNpcsCodeGet
     * @param code The code of the NPC. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getNpcNpcsCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/npcs/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getNpcNpcsCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getNpcNpcsCodeGet(Async)");
        }

        return getNpcNpcsCodeGetCall(code, _callback);

    }

    /**
     * Get Npc
     * Retrieve the details of a NPC.
     * @param code The code of the NPC. (required)
     * @return NPCResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public NPCResponseSchema getNpcNpcsCodeGet(String code) throws ApiException {
        ApiResponse<NPCResponseSchema> localVarResp = getNpcNpcsCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Npc
     * Retrieve the details of a NPC.
     * @param code The code of the NPC. (required)
     * @return ApiResponse&lt;NPCResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<NPCResponseSchema> getNpcNpcsCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getNpcNpcsCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<NPCResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Npc (asynchronously)
     * Retrieve the details of a NPC.
     * @param code The code of the NPC. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched NPC. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> NPC not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getNpcNpcsCodeGetAsync(String code, final ApiCallback<NPCResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getNpcNpcsCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<NPCResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
